---
name: Arrow - build and run tests
author: Danilo Ješić
version: 1

services:
  minimal-ubuntu-venv:
    build:
      context: ./python/examples/minimal_build/
      dockerfile: ./python/examples/minimal_build/Dockerfile.ubuntu
    image: arrow_ubuntu_minimal
    setup-commands:
      - cp -R /tmp/repo /arrow/


flow:
  - name: Build cpp then python
    container: minimal-ubuntu-venv
    commands:
      - type: console
        command: /arrow/python/examples/minimal_build/build_venv.sh
        note: Starting the arrow build